import rclpy
from rclpy.node import Node
from nav_msgs.msg import OccupancyGrid

class SlamMonitor(Node):
    def __init__(self):
        super().__init__('slam_monitor')
        # Subscribes to the /map topic generated by SLAM algorithms
        self.subscription = self.create_subscription(
            OccupancyGrid,
            '/map',
            self.listener_callback,
            10)
        self.get_logger().info('SLAM Monitor Node has started. Waiting for map data...')

    def listener_callback(self, msg):
        # Logs the resolution and size of the generated occupancy grid
        width = msg.info.width
        height = msg.info.height
        resolution = msg.info.resolution
        self.get_logger().info(f'Map Received! Size: {width}x{height} at {resolution}m/px')

def main(args=None):
    rclpy.init(args=args)
    node = SlamMonitor()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
